# Generated by Django 2.2.5 on 2019-09-28 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0002_userposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposition',
            name='id',
        ),
        migrations.AlterField(
            model_name='userposition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
