# Generated by Django 2.2.5 on 2019-09-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0003_auto_20190929_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposition',
            name='user',
        ),
        migrations.AddField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
