# Generated by Django 2.2.5 on 2019-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0004_auto_20190929_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposition',
            name='id',
            field=models.AutoField(auto_created=True,
                                   primary_key=True,
                                   serialize=False,
                                   verbose_name='ID'),
            preserve_default=False,
        ),
    ]
