# Generated by Django 2.2.5 on 2019-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0005_userposition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposition',
            name='fetch_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
