# Generated by Django 2.2.5 on 2019-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0006_userposition_fetch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='fetch_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
