# Generated by Django 2.2.5 on 2019-09-30 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0007_auto_20190930_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='fetch_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
