# Generated by Django 2.2.5 on 2019-10-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_app', '0008_auto_20190930_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('speed', models.DecimalField(decimal_places=0, max_digits=4)),
                ('users', models.ManyToManyField(through='gis_app.UserVehicle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_app.Vehicle'),
        ),
    ]
