# Generated by Django 2.2.5 on 2019-10-04 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_app', '0009_auto_20191004_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservehicle',
            unique_together={('user', 'vehicle')},
        ),
    ]
