# Generated by Django 2.2.5 on 2019-10-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0011_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='users',
            field=models.ManyToManyField(through='gis_app.UserVehicle', to='gis_app.UserAccount'),
        ),
    ]
