# Generated by Django 2.2.5 on 2019-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0012_auto_20191016_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('creating', 'Creating'), ('done', 'Done')], default='new', max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
