# Generated by Django 2.2.5 on 2019-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0013_vehicleexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleexport',
            name='file_path',
            field=models.FilePathField(match='*.pdf', max_length=255, path='/tmp/exports'),
        ),
    ]
