# Generated by Django 2.2.5 on 2019-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0017_auto_20191120_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPositionExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('creating', 'Creating'), ('done', 'Done')], default='new', max_length=255)),
                ('file_path', models.FilePathField(blank=True, match='.*\\.pdf$', max_length=255, path='/workspace/gis_project/pdf_exports')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vehicleexport',
            name='file_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', max_length=255, path='/workspace/gis_project/pdf_exports'),
        ),
    ]
