version: '3.3'
services:
 db:
  image: postgres:10.0-alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: gis_user123
 redis:
  container_name: redis
  image: redis:5.0.6-alpine
  ports:
     - "6379:6379"
  entrypoint: redis-server --appendonly yes
  restart: always
 rabbitmq:
  image: rabbitmq:3.8.0-alpine
  command: rabbitmq-server
  expose:
    - 5672
    - 15672
  healthcheck:
    test: [ "CMD", "nc", "-z", "localhost", "5672" ]
    interval: 5s
    timeout: 15s
    retries: 1
 web:
   build: .
   command: sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 gis_project.wsgi"
   environment:
    DJANGO_SETTINGS_MODULE: gis_project.settings.local
   volumes:
     - "$PWD/gis_project:/code"
   ports:
     - "8000:8000"
   depends_on:
     - db
     - redis
     - rabbitmq
 celery:
   build: .
   command: celery -A gis_project worker -l info
   environment:
    DJANGO_SETTINGS_MODULE: gis_project.settings.local
   volumes:
     - "$PWD/gis_project:/code"
   depends_on:
     - db
     - redis
     - rabbitmq
 flower:  
   image: mher/flower
   environment:
     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
     - FLOWER_PORT=8888
   ports:  
     - 8888:8888