version: '3.3'
services:
 db:
  image: postgres
 redis:
  container_name: redis
  image: redis
  ports:
     - "6379:6379"
  entrypoint: redis-server --appendonly yes
  restart: always
 rabbitmq:
  image: rabbitmq
  command: rabbitmq-server
  expose:
    - 5672
    - 15672
  healthcheck:
    test: [ "CMD", "nc", "-z", "localhost", "5672" ]
    interval: 5s
    timeout: 15s
    retries: 1
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - "$PWD/gis_project:/project"
   ports:
     - "8000:8000"
   depends_on:
     - db
     - redis
     - rabbitmq
 celery:
   build: .
   command: celery -A gis_project worker -l info
   volumes:
     - "$PWD/gis_project:/project"
   depends_on:
     - db
     - redis
     - rabbitmq
 flower:  
   image: mher/flower
   environment:
     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
     - FLOWER_PORT=8888
   ports:  
     - 8888:8888